export const TODOS_REQUESTING = 'TODOS_REQUESTING';
export const TODOS_REQUEST_SUCCESS = 'TODOS_REQUEST_SUCCESS';
export const TODOS_REQUEST_ERROR = 'TODOS_REQUEST_ERROR';
export const RESET_TODOS_REQUEST = 'RESET_TODOS_REQUEST';
